# Generated by Django 3.1 on 2020-10-29 06:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=None, editable=False)),
                ('modified', models.DateTimeField(default=None, editable=False)),
                ('uid', models.CharField(editable=False, max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('display_name', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('git_id', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=None, editable=False)),
                ('modified', models.DateTimeField(default=None, editable=False)),
                ('uid', models.CharField(editable=False, max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('display_name', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="{'class': 'category', 'model_name': 'category', 'app_label': 'main'}(class)s_created+", to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="{'class': 'category', 'model_name': 'category', 'app_label': 'main'}(class)s_modified+", to=settings.AUTH_USER_MODEL)),
                ('owned_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="{'class': 'category', 'model_name': 'category', 'app_label': 'main'}(class)s_owned+", to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_categories', to='main.category')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=None, editable=False)),
                ('modified', models.DateTimeField(default=None, editable=False)),
                ('payload', models.JSONField(default=dict)),
                ('kind', models.CharField(choices=[('ssh', 'Machine'), ('scm', 'Source Control'), ('cloud', 'Cloud'), ('kubernetes', 'Kubernetes')], default='ssh', max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Env',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=None, editable=False)),
                ('modified', models.DateTimeField(default=None, editable=False)),
                ('uid', models.CharField(editable=False, max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('display_name', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="{'class': 'env', 'model_name': 'env', 'app_label': 'main'}(class)s_created+", to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="{'class': 'env', 'model_name': 'env', 'app_label': 'main'}(class)s_modified+", to=settings.AUTH_USER_MODEL)),
                ('owned_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="{'class': 'env', 'model_name': 'env', 'app_label': 'main'}(class)s_owned+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='OrchestrationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=None, editable=False)),
                ('modified', models.DateTimeField(default=None, editable=False)),
                ('uid', models.CharField(editable=False, max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('display_name', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('kind', models.CharField(max_length=64)),
                ('created_by', models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="{'class': 'orchestrationtype', 'model_name': 'orchestrationtype', 'app_label': 'main'}(class)s_created+", to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="{'class': 'orchestrationtype', 'model_name': 'orchestrationtype', 'app_label': 'main'}(class)s_modified+", to=settings.AUTH_USER_MODEL)),
                ('owned_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="{'class': 'orchestrationtype', 'model_name': 'orchestrationtype', 'app_label': 'main'}(class)s_owned+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Orchestrator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=None, editable=False)),
                ('modified', models.DateTimeField(default=None, editable=False)),
                ('uid', models.CharField(editable=False, max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('display_name', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="{'class': 'orchestrator', 'model_name': 'orchestrator', 'app_label': 'main'}(class)s_created+", to=settings.AUTH_USER_MODEL)),
                ('env', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Orchestrator', to='main.env')),
                ('modified_by', models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="{'class': 'orchestrator', 'model_name': 'orchestrator', 'app_label': 'main'}(class)s_modified+", to=settings.AUTH_USER_MODEL)),
                ('owned_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="{'class': 'orchestrator', 'model_name': 'orchestrator', 'app_label': 'main'}(class)s_owned+", to=settings.AUTH_USER_MODEL)),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.orchestrationtype')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=None, editable=False)),
                ('modified', models.DateTimeField(default=None, editable=False)),
                ('ldap_dn', models.CharField(default='', max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Workload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=None, editable=False)),
                ('modified', models.DateTimeField(default=None, editable=False)),
                ('uid', models.CharField(editable=False, max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('display_name', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(max_length=32)),
                ('app', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workloads', to='main.app')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workloads', to='main.category')),
                ('created_by', models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="{'class': 'workload', 'model_name': 'workload', 'app_label': 'main'}(class)s_created+", to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="{'class': 'workload', 'model_name': 'workload', 'app_label': 'main'}(class)s_modified+", to=settings.AUTH_USER_MODEL)),
                ('orchestrator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workloads', to='main.orchestrator')),
                ('owned_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="{'class': 'workload', 'model_name': 'workload', 'app_label': 'main'}(class)s_owned+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=None, editable=False)),
                ('modified', models.DateTimeField(default=None, editable=False)),
                ('uid', models.CharField(editable=False, max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('display_name', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.CharField(max_length=128)),
                ('due_date', models.DateTimeField(default=None)),
                ('app', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='releases', to='main.app')),
                ('created_by', models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="{'class': 'release', 'model_name': 'release', 'app_label': 'main'}(class)s_created+", to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="{'class': 'release', 'model_name': 'release', 'app_label': 'main'}(class)s_modified+", to=settings.AUTH_USER_MODEL)),
                ('owned_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="{'class': 'release', 'model_name': 'release', 'app_label': 'main'}(class)s_owned+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=None, editable=False)),
                ('modified', models.DateTimeField(default=None, editable=False)),
                ('uid', models.CharField(editable=False, max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('display_name', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('pipeline_id', models.PositiveIntegerField(blank=True, null=True)),
                ('params', models.JSONField(default=dict)),
                ('app', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deployments', to='main.app')),
                ('created_by', models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="{'class': 'deployment', 'model_name': 'deployment', 'app_label': 'main'}(class)s_created+", to=settings.AUTH_USER_MODEL)),
                ('env', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deployments', to='main.env')),
                ('modified_by', models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="{'class': 'deployment', 'model_name': 'deployment', 'app_label': 'main'}(class)s_modified+", to=settings.AUTH_USER_MODEL)),
                ('owned_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="{'class': 'deployment', 'model_name': 'deployment', 'app_label': 'main'}(class)s_owned+", to=settings.AUTH_USER_MODEL)),
                ('release', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deployments', to='main.release')),
                ('workload', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.workload')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='app',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apps', to='main.category'),
        ),
        migrations.AddField(
            model_name='app',
            name='created_by',
            field=models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="{'class': 'app', 'model_name': 'app', 'app_label': 'main'}(class)s_created+", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='app',
            name='modified_by',
            field=models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="{'class': 'app', 'model_name': 'app', 'app_label': 'main'}(class)s_modified+", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='app',
            name='owned_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="{'class': 'app', 'model_name': 'app', 'app_label': 'main'}(class)s_owned+", to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Cloud',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.credential',),
        ),
        migrations.CreateModel(
            name='Kubernetes',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.credential',),
        ),
        migrations.CreateModel(
            name='Scm',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.credential',),
        ),
        migrations.CreateModel(
            name='Ssh',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.credential',),
        ),
    ]
