# Generated by Django 3.1 on 2020-10-31 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orchestrator',
            name='env',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Orchestrator', to='main.env', to_field='uid'),
        ),
    ]
