# Generated by Django 3.1 on 2020-10-31 02:42

import apps.main.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201031_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='category',
            field=apps.main.fields.UidForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apps', to='main.category', to_field='uid'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=apps.main.fields.UidForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_categories', to='main.category', to_field='uid'),
        ),
        migrations.AlterField(
            model_name='orchestrator',
            name='env',
            field=apps.main.fields.UidForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Orchestrator', to='main.env', to_field='uid'),
        ),
        migrations.AlterField(
            model_name='orchestrator',
            name='type',
            field=apps.main.fields.UidForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.orchestrationtype', to_field='uid'),
        ),
        migrations.AlterField(
            model_name='workload',
            name='app',
            field=apps.main.fields.UidForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workloads', to='main.app', to_field='uid'),
        ),
        migrations.AlterField(
            model_name='workload',
            name='category',
            field=apps.main.fields.UidForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workloads', to='main.category', to_field='uid'),
        ),
        migrations.AlterField(
            model_name='workload',
            name='orchestrator',
            field=apps.main.fields.UidForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workloads', to='main.orchestrator', to_field='uid'),
        ),
    ]
